server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/movie_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    enabled: false
app:
  cors:
    allowed-origins: http://localhost:5173
file:
  upload:
    dir: uploads/movies
    max-size: 52428800
    allowed-types:
      - image/jpeg
      - image/jpg
      - image/png
      - image/webp
      - video/mp4
      - video/mpeg
      - video/quicktime
      - video/x-msvideo
      - video/webm
